language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

install:
  - sh .travis.install.sh

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test/

matrix:
  allow_failures:
    - php: 7
    - php: hhvm

after_script:
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" == '5.6' ]]; then php ocular.phar code-coverage:upload --format=php-clover ./clover.xml; fi

